In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_excel('CianDataset2020.xlsx')
print(df_train)

                                           url           date_saved District1  \
0      https://www.cian.ru/sale/flat/11825143/  2020-04-27 00:08:05      ЮВАО
1      https://www.cian.ru/sale/flat/12047605/  2020-04-29 01:01:33       САО
2      https://www.cian.ru/sale/flat/12108103/  2020-05-18 19:08:01       ЦАО
3       https://www.cian.ru/sale/flat/1217743/  2020-04-30 12:20:18       САО
4      https://www.cian.ru/sale/flat/12939895/  2020-05-01 21:10:36       САО
...                                        ...                  ...       ...
51585  https://www.cian.ru/sale/flat/51105793/  2020-05-19 21:46:02       ВАО
51586  https://www.cian.ru/sale/flat/51936209/  2020-05-20 01:06:11      ЮЗАО
51587   https://www.cian.ru/sale/flat/6651416/  2020-04-26 14:01:07       САО
51588    https://www.cian.ru/sale/flat/889171/  2020-04-28 12:32:29      СЗАО
51589   https://www.cian.ru/sale/flat/9331361/  2020-04-28 13:30:17       ЦАО

      District2                                     ad_breadCrumbs  \
0          ЮВАО  Недвижимость в Москве, Продажа, Продажа 3-комн...
1           САО  Недвижимость в Москве, Продажа, Продажа 3-комн...
2           ЦАО  Недвижимость в Москве, Продажа, Продажа 2-комн...
3           САО  Недвижимость в Москве, Продажа, Продажа 3-комн...
4           САО  Недвижимость в Москве, Продажа, Продажа 2-комн...
...         ...                                                ...
51585       ВАО  Недвижимость в Москве, Продажа, Продажа 2-комн...
51586      ЮЗАО  Недвижимость в Москве, Продажа, Продажа 3-комн...
51587       САО  Недвижимость в Москве, Продажа, Продажа 3-комн...
51588      СЗАО  Недвижимость в Москве, Продажа, Продажа 3-комн...
51589       ЦАО  Недвижимость в Москве, Продажа, Продажа 3-комн...

            ad_change_time ad_objectType  ad_offerPhone    ad_price  \
0      2020-03-20 12:03:00      flat_old   7.985997e+10  18800000.0
1      2020-03-16 14:40:58      flat_old   7.916812e+10  50000000.0
2      2020-03-03 23:34:16      flat_old            NaN  55000000.0
3                      NaN      flat_old   7.964500e+10         NaN
4                      NaN      flat_old   7.964500e+10         NaN
...                    ...           ...            ...         ...
51585  2019-10-03 15:36:21      flat_old   7.925446e+10   7850000.0
51586  2019-06-17 11:27:07      flat_old   7.926987e+10  32500000.0
51587  2019-10-01 08:35:10      flat_old   7.909933e+10   1275000.0
51588  2020-02-20 14:30:05      flat_old   7.903125e+10  33500000.0
51589  2020-04-04 13:20:25      flat_old   7.964500e+10   2000000.0

      ad_price_cur  ...  offer_similarOffersCount  offer_status offer_title  \
0              rur  ...                         0     published         NaN
1              rur  ...                         0     published         NaN
2              rur  ...                         0         draft         NaN
3              NaN  ...                         0     published         NaN
4              NaN  ...                         0     published         NaN
...            ...  ...                       ...           ...         ...
51585          rur  ...                         0     published         NaN
51586          rur  ...                         0     published         NaN
51587          usd  ...                         0     published         NaN
51588          rur  ...                         0     published         NaN
51589          usd  ...                         0     published         NaN

       offer_totalArea  offer_valueAddedServices_isColorized  \
0                106.0                                 False
1                130.0                                 False
2                108.5                                 False
3                 87.0                                 False
4                 55.0                                 False
...                ...                                   ...
51585             45.0                                 False
51586             80.0                                 False
51587            128.0                                 False
51588            113.0                                 False
51589            138.0                                 False

       offer_valueAddedServices_isPaid  offer_valueAddedServices_isPremium  \
0                                 True                               False
1                                 True                               False
2                                False                               False
3                                 True                               False
4                                 True                               False
...                                ...                                 ...
51585                             True                               False
51586                             True                               False
51587                             True                               False
51588                             True                               False
51589                             True                               False

       offer_valueAddedServices_isTop3  offer_wcType  offer_windowsViewType
0                                False           NaN          yardAndStreet
1                                False           NaN          yardAndStreet
2                                False           NaN                 street
3                                False           NaN          yardAndStreet
4                                False           NaN                   yard
...                                ...           ...                    ...
51585                            False           NaN                 street
51586                            False           NaN                   yard
51587                            False           NaN          yardAndStreet
51588                            False           NaN                   yard
51589                            False           NaN                   yard

[51590 rows x 225 columns]

In [3]:
df_train1=df_train.drop(columns=['offer_livingArea','offer_kitchenArea','offer_geo_railways_7_travelType','offer_building_hasGarbageChute','offer_building_buildYear','offer_bargainTerms_prices_usd','offer_bargainTerms_prices_rur','offer_bargainTerms_prices_eur','bti_district_regionTitle','offer_bargainTerms_leaseTermType','offer_balconiesCount','offer_building_materialType','offer_building_houseMaterialType','District2','ad_change_time','offer_wcType','offer_combinedWcsCount','url','date_saved','ad_breadCrumbs','ad_offerPhone','ad_price_cur','agent_isCianPartner','agent_isDeveloper','agent_isPrivateBroker','agent_isPro','agent_isRecidivist','agent_isSelfEmployed','agent_isSubAgent','agent_isUserOffersHasErrors','agent_userType','bti_house_houseOverhaulFundType','bti_house_isEmergency','bti_house_seriesName','company_newobjectsCount','company_offersCount','company_yearFoundation','newObject_stats_done','newObject_stats_progress','newObject_status','offer_added','offer_allRoomsArea','offer_archivedDate','offer_bargainTerms_agentBonus_currency','offer_bargainTerms_agentBonus_paymentType','offer_bargainTerms_agentBonus_value','offer_bargainTerms_currency','offer_bargainTerms_deposit','offer_bargainTerms_depositPrices_eur','offer_bargainTerms_depositPrices_rur','offer_bargainTerms_depositPrices_usd','offer_bargainTerms_saleType','offer_breadCrumbs','offer_building_ceilingHeight','offer_building_deadline_isComplete','offer_building_deadline_quarter','offer_building_deadline_quarterEnd','offer_building_deadline_year','offer_building_name','offer_building_parking_type','offer_building_passengerLiftsCount','offer_building_series','offer_cargoLiftsCount','offer_category','offer_deadline_isComplete','offer_deadline_quarter','offer_deadline_quarterEnd','offer_deadline_year','offer_decoration','offer_demolishedInMoscowProgramm','offer_description','offer_editDate','offer_flatType','offer_geo_highways_1_distance','offer_geo_highways_1_name','offer_geo_highways_2_distance','offer_geo_highways_2_name','offer_geo_highways_3_distance','offer_geo_highways_3_name','offer_geo_jk_displayName','offer_geo_railways_10_name','offer_geo_railways_10_time','offer_geo_railways_10_travelType','offer_geo_railways_11_name','offer_geo_railways_11_time','offer_geo_railways_11_travelType','offer_geo_railways_12_name','offer_geo_railways_12_time','offer_geo_railways_12_travelType','offer_geo_railways_7_name','offer_geo_railways_7_time','offer_geo_railways_7_time','offer_geo_railways_8_name','offer_geo_railways_8_time','offer_geo_railways_8_travelType','offer_geo_railways_9_name','offer_geo_railways_9_time','offer_geo_railways_9_travelType','offer_geo_undergrounds_1_releaseYear','offer_geo_undergrounds_2_lineColor','offer_geo_undergrounds_2_name','offer_geo_undergrounds_2_releaseYear','offer_geo_undergrounds_2_travelTime','offer_geo_undergrounds_2_travelType','offer_geo_undergrounds_2_underConstruction','offer_geo_undergrounds_3_name','offer_geo_undergrounds_3_releaseYear','offer_geo_undergrounds_3_lineColor','offer_geo_undergrounds_3_travelTime','offer_geo_undergrounds_3_travelType','offer_geo_undergrounds_3_underConstruction','offer_hasFurniture','offer_hasPhone','offer_hasRamp','offer_homeownerProofs','offer_isApartments','offer_isByHomeowner','offer_isFromBuilder','offer_isFromSeller','offer_isImported','offer_isInHiddenBase','offer_isPenthouse','offer_loggiasCount','offer_newbuilding_house_isFinished','offer_newbuilding_house_isReliable','offer_newbuilding_house_name','offer_newbuilding_isFromBuilder','offer_newbuilding_isFromDeveloper','offer_newbuilding_isFromLeadFactory','offer_newbuilding_isFromSeller','offer_newbuilding_isReliable','offer_newbuilding_name','offer_newbuilding_newbuildingFeatures_deadlineInfo','offer_newbuilding_newbuildingFeatures_imagesCount','offer_newbuilding_newbuildingFeatures_videosCount','offer_newbuilding_showJkReliableFlag','offer_passengerLiftsCount','offer_promoLabel','offer_publicationDate','offer_publishTerms_autoprolong','offer_publishTerms_terms_days','offer_publishTerms_terms_services','offer_publishTerms_terms_tariff','offer_publishTerms_terms_type','offer_rentByPartsDescription','offer_repairType','offer_roomType','offer_roomsForSaleCount','offer_rosreestrCheck','offer_separateWcsCount','offer_status','offer_title','offer_valueAddedServices_isColorized','offer_valueAddedServices_isPaid','offer_valueAddedServices_isPremium','offer_windowsViewType'])

In [4]:
df_train1.columns

Index(['District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_accountType', 'agent_offersCount',
       'agent_userTrustLevel', 'bti_district_avgHouseAge',
       'bti_district_districtTitle', 'bti_district_priceSqm',
       'bti_district_priceSqmDiff', 'bti_district_roomRentPrice',
       'bti_district_roomRentPriceDiff', 'bti_district_roomSalePrice',
       'bti_district_roomSalePriceDiff',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_entrances',
       'bti_house_flatCount', 'bti_house_floorMax',
       'bti_house_houseGasSupplyType', 'bti_house_houseHeatSupplyType',
       'bti_house_houseMaterialType', 'bti_house_houseOverlapType',
       'bti_house_lifts', 'bti_house_priceCian', 'bti_house_priceCianMax',
       'bti_house_priceCianMin', 'bti_house_priceSqm',
       'bti_house_priceSqmDiff', 'bti_house_roomRentPrice',
       'bti_house_roomRentPriceDiff', 'bti_house_yearRelease',
       'demandJsonQuery_price_gte', 'demandJsonQuery_price_lte',
       'offer_bargainTerms_mortgageAllowed', 'offer_bargainTerms_price',
       'offer_building_cargoLiftsCount', 'offer_building_floorsCount',
       'offer_building_totalArea', 'offer_floorNumber',
       'offer_geo_coordinates_lat', 'offer_geo_coordinates_lng',
       'offer_geo_railways_1_name', 'offer_geo_railways_1_time',
       'offer_geo_railways_1_travelType', 'offer_geo_railways_2_name',
       'offer_geo_railways_2_time', 'offer_geo_railways_2_travelType',
       'offer_geo_railways_3_name', 'offer_geo_railways_3_time',
       'offer_geo_railways_3_travelType', 'offer_geo_railways_4_name',
       'offer_geo_railways_4_time', 'offer_geo_railways_4_travelType',
       'offer_geo_railways_5_name', 'offer_geo_railways_5_time',
       'offer_geo_railways_5_travelType', 'offer_geo_railways_6_name',
       'offer_geo_railways_6_time', 'offer_geo_railways_6_travelType',
       'offer_geo_undergrounds_1_lineColor', 'offer_geo_undergrounds_1_name',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3'],
      dtype='object')

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.model_selection import GridSearchCV

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import MinMaxScaler, StandardScaler, RobustScaler
from sklearn.model_selection import train_test_split, cross_val_score, GridSearchCV, KFold 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn import svm
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.preprocessing import PolynomialFeatures
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score

In [7]:
# обязательный код
df=df_train1.copy()
X=df.drop(columns=['ad_price']).values
y=df.ad_price.values
# сплитуйте X и y как хотите
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state=0, 
                                                    shuffle=True, stratify = df_train.ad_price)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [39]:
import math


def distance(lat1,lon1,lat2,lon2):

    radius = 6371  # km

    dlat = math.radians(lat2 - lat1)
    dlon = math.radians(lon2 - lon1)
    a = (math.sin(dlat / 2) * math.sin(dlat / 2) +
         math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) *
         math.sin(dlon / 2) * math.sin(dlon / 2))
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    d = radius * c

    return d
def mp_cal(lat1,lon1,lat2,lon2):
    if distance(lat1,lon1,lat2,lon2)==0:
        first_step=0
    else:
        first_step=1/distance(lat1,lon1,lat2,lon2)
        return first_step

In [23]:
column_np=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_br.latitude, df_br.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))
    column_np=np.append(column_np,sum(Pls))
new=list(column_np)
df_train1['mp_br']=new

TypeError: unsupported operand type(s) for -: 'str' and 'float'

In [41]:
column_np=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_br.latitude, df_br.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np=np.append(column_np,sum(e))
new=list(column_np)
df_train1['mp_br']=new

In [35]:
df_br=pd.read_excel('df_br.xlsx')

In [36]:
df_br

      Unnamed: 0  longitude   latitude
0              0  37.809479  55.700410
1              1  37.616243  55.729351
2              2  37.621741  55.727526
3              3  37.612173  55.711240
4              4  37.597127  55.766937
...          ...        ...        ...
1000        1000  37.566764  55.752323
1001        1001  37.559954  55.756614
1002        1002  37.620869  55.732200
1003        1003  37.586796  55.778193
1004        1004  37.562308  55.796046

[1005 rows x 3 columns]

In [42]:
df_train1.mp_br

0         79.828361
1        156.518341
2        239.967013
3        227.641826
4        218.409409
            ...
51585    104.872249
51586    139.330478
51587    192.414057
51588     97.302992
51589    323.264825
Name: mp_br, Length: 51590, dtype: float64

In [43]:
df_cs=pd.read_excel('df_cs.xlsx')

In [44]:
column_np1=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_cs.latitude, df_cs.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np1=np.append(column_np1,sum(e))
new1=list(column_np1)
df_train1['mp_cs']=new1

In [47]:
df_gs=pd.read_excel('df_gs.xlsx')

In [48]:
column_np2=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_gs.latitude, df_gs.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np2=np.append(column_np2,sum(e))
new2=list(column_np2)
df_train1['mp_gs']=new2

In [49]:
df_m=pd.read_excel('df_m.xlsx')

In [50]:
column_np3=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_m.latitude, df_m.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np3=np.append(column_np3,sum(e))
new3=list(column_np3)
df_train1['mp_m']=new3

In [51]:
df_sm=pd.read_excel('df_sm.xlsx')

In [52]:
column_np4=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_sm.latitude, df_sm.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np4=np.append(column_np4,sum(e))
new4=list(column_np4)
df_train1['mp_sm']=new4

In [53]:
df_t=pd.read_excel('df_t.xlsx')

In [54]:
column_np5=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_t.latitude, df_t.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np5=np.append(column_np5,sum(e))
new5=list(column_np5)
df_train1['mp_t']=new5

In [55]:
df_k=pd.read_excel('df_k.xlsx')

In [56]:
column_np6=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_k.latitude, df_k.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np6=np.append(column_np6,sum(e))
new6=list(column_np6)
df_train1['mp_k']=new6

In [57]:
df_p=pd.read_excel('df_p.xlsx')

In [58]:
column_np7=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_p.latitude, df_p.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np7=np.append(column_np7,sum(e))
new7=list(column_np7)
df_train1['mp_p']=new7

In [59]:
df_u=pd.read_excel('df_u.xlsx')

In [60]:
column_np8=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_u.latitude, df_u.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np8=np.append(column_np8,sum(e))
new8=list(column_np8)
df_train1['mp_u']=new8

In [61]:
df_h=pd.read_excel('df_h.xlsx')

In [62]:
column_np9=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_h.latitude, df_h.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np9=np.append(column_np9,sum(e))
new9=list(column_np9)
df_train1['mp_h']=new9

In [64]:
df_oc=pd.read_excel('df_oc.xlsx')

In [65]:
column_np10=np.array([])
for lat1,lon1 in zip(df_train1.offer_geo_coordinates_lat, df_train1.offer_geo_coordinates_lng):
    Pls=np.array([])
    for lat2,lon2 in zip(df_oc.latitude, df_oc.longitude):
        Pls=np.append(Pls,mp_cal(lat1,lon1,lat2,lon2))

        e = np.array([])
    for i in Pls:
        if i is None: 
            e=np.append(e,0)
        else:
            e=np.append(e,i)
    column_np10=np.append(column_np10,sum(e))
new10=list(column_np10)
df_train1['mp_oc']=new10

In [68]:
df_train1.to_excel('df_train.xlsx')

In [74]:
df_train1['mp']=df_train1.mp_br+df_train1.mp_cs+df_train1.mp_gs+df_train1.mp_m+df_train1.mp_sm+df_train1.mp_t+df_train1.mp_k+df_train1.mp_p+df_train1.mp_u+df_train1.mp_h+df_train1.mp_oc

In [76]:
df_train1

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_accountType,agent_offersCount,agent_userTrustLevel,bti_district_avgHouseAge,bti_district_districtTitle,...,mp_gs,mp_m,mp_sm,mp_t,mp_k,mp_p,mp_u,mp_h,mp_oc,mp
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,specialist,5.0,notInvolved,27.0,Марьино,...,95.190480,32.695287,86.773529,23.300874,15.872278,18.884448,81.502214,7.607428e+01,7.875472e+01,6.684463e+02
1,САО,flat_old,50000000.0,1.0,2289.0,specialist,8.0,notInvolved,47.0,Хорошёвский,...,118.991528,30.177616,85.161920,44.361699,24.514948,47.922971,172.025187,1.265683e+12,1.265683e+12,2.531365e+12
2,ЦАО,flat_old,55000000.0,0.0,2745.0,agency,31.0,involved,NaN,NaN,...,161.082642,36.389239,100.283235,73.234226,34.307251,46.562756,200.941529,2.375098e+02,2.075447e+02,1.538714e+03
3,САО,flat_old,NaN,0.0,807.0,specialist,4.0,notInvolved,47.0,Хорошёвский,...,165.101833,31.637746,96.170120,64.344462,27.423835,44.917454,203.606628,2.217018e+02,1.265683e+12,1.265683e+12
4,САО,flat_old,NaN,0.0,903.0,specialist,4.0,notInvolved,47.0,Хорошёвский,...,162.311831,31.775466,120.586512,63.034387,27.476007,44.733774,200.336818,2.168273e+02,2.290378e+02,1.536077e+03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51585,ВАО,flat_old,7850000.0,15.0,10527.0,specialist,6.0,notInvolved,53.0,Перово,...,148.029413,32.995538,88.570743,30.202956,17.906718,19.946484,105.133421,1.052016e+02,1.132088e+02,8.723399e+02
51586,ЮЗАО,flat_old,32500000.0,0.0,2409.0,specialist,19.0,involved,46.0,Обручевский,...,90.844283,32.335390,474.698703,27.944573,20.657448,32.844238,99.487188,2.887726e+02,9.746858e+01,1.399602e+03
51587,САО,flat_old,1275000.0,2.0,3513.0,agency,36.0,involved,57.0,Аэропорт,...,157.870324,31.308698,103.905542,59.665138,25.093171,43.005483,203.336200,2.072354e+02,2.083797e+02,1.418570e+03
51588,СЗАО,flat_old,33500000.0,7.0,1839.0,agency,26.0,involved,54.0,Щукино,...,76.345518,25.028516,73.651870,26.828472,18.565519,34.953011,92.365431,9.182253e+01,9.175479e+01,7.076008e+02
51589,ЦАО,flat_old,2000000.0,0.0,322.0,specialist,4.0,notInvolved,87.0,Басманный,...,289.835471,38.883873,105.586534,109.219862,33.177196,48.534463,342.154912,3.922431e+02,3.740926e+02,2.518113e+03

In [81]:
df_train1.to_excel('df_train_new.xlsx')

AttributeError: 'NoneType' object has no attribute 'isna'

In [84]:
nan_value = float("NaN")
df_train1.replace("", nan_value, inplace=True)

In [85]:
df_train1.isna().sum()

District1          6
ad_objectType      0
ad_price         142
ad_stat_daily     75
ad_stat_total     75
                ...
mp_p               0
mp_u               0
mp_h               0
mp_oc              0
mp                 0
Length: 82, dtype: int64

In [87]:
df_train1.columns

Index(['District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_accountType', 'agent_offersCount',
       'agent_userTrustLevel', 'bti_district_avgHouseAge',
       'bti_district_districtTitle', 'bti_district_priceSqm',
       'bti_district_priceSqmDiff', 'bti_district_roomRentPrice',
       'bti_district_roomRentPriceDiff', 'bti_district_roomSalePrice',
       'bti_district_roomSalePriceDiff',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_entrances',
       'bti_house_flatCount', 'bti_house_floorMax',
       'bti_house_houseGasSupplyType', 'bti_house_houseHeatSupplyType',
       'bti_house_houseMaterialType', 'bti_house_houseOverlapType',
       'bti_house_lifts', 'bti_house_priceCian', 'bti_house_priceCianMax',
       'bti_house_priceCianMin', 'bti_house_priceSqm',
       'bti_house_priceSqmDiff', 'bti_house_roomRentPrice',
       'bti_house_roomRentPriceDiff', 'bti_house_yearRelease',
       'demandJsonQuery_price_gte', 'demandJsonQuery_price_lte',
       'offer_bargainTerms_mortgageAllowed', 'offer_bargainTerms_price',
       'offer_building_cargoLiftsCount', 'offer_building_floorsCount',
       'offer_building_totalArea', 'offer_floorNumber',
       'offer_geo_coordinates_lat', 'offer_geo_coordinates_lng',
       'offer_geo_railways_1_name', 'offer_geo_railways_1_time',
       'offer_geo_railways_1_travelType', 'offer_geo_railways_2_name',
       'offer_geo_railways_2_time', 'offer_geo_railways_2_travelType',
       'offer_geo_railways_3_name', 'offer_geo_railways_3_time',
       'offer_geo_railways_3_travelType', 'offer_geo_railways_4_name',
       'offer_geo_railways_4_time', 'offer_geo_railways_4_travelType',
       'offer_geo_railways_5_name', 'offer_geo_railways_5_time',
       'offer_geo_railways_5_travelType', 'offer_geo_railways_6_name',
       'offer_geo_railways_6_time', 'offer_geo_railways_6_travelType',
       'offer_geo_undergrounds_1_lineColor', 'offer_geo_undergrounds_1_name',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3', 'mp_br', 'mp_cs', 'mp_gs', 'mp_m',
       'mp_sm', 'mp_t', 'mp_k', 'mp_p', 'mp_u', 'mp_h', 'mp_oc', 'mp'],
      dtype='object')

In [111]:
df_train = pd.read_excel('df_train_new.xlsx')
print(df_train)

       Unnamed: 0 District1 ad_objectType    ad_price  ad_stat_daily  \
0               0      ЮВАО      flat_old  18800000.0            3.0
1               1       САО      flat_old  50000000.0            1.0
2               2       ЦАО      flat_old  55000000.0            0.0
3               3       САО      flat_old         NaN            0.0
4               4       САО      flat_old         NaN            0.0
...           ...       ...           ...         ...            ...
51585       51585       ВАО      flat_old   7850000.0           15.0
51586       51586      ЮЗАО      flat_old  32500000.0            0.0
51587       51587       САО      flat_old   1275000.0            2.0
51588       51588      СЗАО      flat_old  33500000.0            7.0
51589       51589       ЦАО      flat_old   2000000.0            0.0

       ad_stat_total agent_accountType  agent_offersCount  \
0             5364.0        specialist                5.0
1             2289.0        specialist                8.0
2             2745.0            agency               31.0
3              807.0        specialist                4.0
4              903.0        specialist                4.0
...              ...               ...                ...
51585        10527.0        specialist                6.0
51586         2409.0        specialist               19.0
51587         3513.0            agency               36.0
51588         1839.0            agency               26.0
51589          322.0        specialist                4.0

      agent_userTrustLevel  bti_district_avgHouseAge  ...       mp_gs  \
0              notInvolved                      27.0  ...   95.190480
1              notInvolved                      47.0  ...  118.991528
2                 involved                       NaN  ...  161.082642
3              notInvolved                      47.0  ...  165.101833
4              notInvolved                      47.0  ...  162.311831
...                    ...                       ...  ...         ...
51585          notInvolved                      53.0  ...  148.029413
51586             involved                      46.0  ...   90.844283
51587             involved                      57.0  ...  157.870324
51588             involved                      54.0  ...   76.345518
51589          notInvolved                      87.0  ...  289.835471

            mp_m       mp_sm        mp_t       mp_k       mp_p        mp_u  \
0      32.695287   86.773529   23.300874  15.872278  18.884448   81.502214
1      30.177616   85.161920   44.361699  24.514948  47.922971  172.025187
2      36.389239  100.283235   73.234226  34.307251  46.562756  200.941529
3      31.637746   96.170120   64.344462  27.423835  44.917454  203.606628
4      31.775466  120.586512   63.034387  27.476007  44.733774  200.336818
...          ...         ...         ...        ...        ...         ...
51585  32.995538   88.570743   30.202956  17.906718  19.946484  105.133421
51586  32.335390  474.698703   27.944573  20.657448  32.844238   99.487188
51587  31.308698  103.905542   59.665138  25.093171  43.005483  203.336200
51588  25.028516   73.651870   26.828472  18.565519  34.953011   92.365431
51589  38.883873  105.586534  109.219862  33.177196  48.534463  342.154912

               mp_h         mp_oc            mp
0      7.607428e+01  7.875472e+01  6.684463e+02
1      1.265683e+12  1.265683e+12  2.531365e+12
2      2.375098e+02  2.075447e+02  1.538714e+03
3      2.217018e+02  1.265683e+12  1.265683e+12
4      2.168273e+02  2.290378e+02  1.536077e+03
...             ...           ...           ...
51585  1.052016e+02  1.132088e+02  8.723399e+02
51586  2.887726e+02  9.746858e+01  1.399602e+03
51587  2.072354e+02  2.083797e+02  1.418570e+03
51588  9.182253e+01  9.175479e+01  7.076008e+02
51589  3.922431e+02  3.740926e+02  2.518113e+03

[51590 rows x 83 columns]

In [7]:
count_nan = len(df_train) - df_train.offer_geo_railways_1_travelType.count()
count_nan

763

In [112]:
df_train.columns

Index(['Unnamed: 0', 'District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_accountType', 'agent_offersCount',
       'agent_userTrustLevel', 'bti_district_avgHouseAge',
       'bti_district_districtTitle', 'bti_district_priceSqm',
       'bti_district_priceSqmDiff', 'bti_district_roomRentPrice',
       'bti_district_roomRentPriceDiff', 'bti_district_roomSalePrice',
       'bti_district_roomSalePriceDiff',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_entrances',
       'bti_house_flatCount', 'bti_house_floorMax',
       'bti_house_houseGasSupplyType', 'bti_house_houseHeatSupplyType',
       'bti_house_houseMaterialType', 'bti_house_houseOverlapType',
       'bti_house_lifts', 'bti_house_priceCian', 'bti_house_priceCianMax',
       'bti_house_priceCianMin', 'bti_house_priceSqm',
       'bti_house_priceSqmDiff', 'bti_house_roomRentPrice',
       'bti_house_roomRentPriceDiff', 'bti_house_yearRelease',
       'demandJsonQuery_price_gte', 'demandJsonQuery_price_lte',
       'offer_bargainTerms_mortgageAllowed', 'offer_bargainTerms_price',
       'offer_building_cargoLiftsCount', 'offer_building_floorsCount',
       'offer_building_totalArea', 'offer_floorNumber',
       'offer_geo_coordinates_lat', 'offer_geo_coordinates_lng',
       'offer_geo_railways_1_name', 'offer_geo_railways_1_time',
       'offer_geo_railways_1_travelType', 'offer_geo_railways_2_name',
       'offer_geo_railways_2_time', 'offer_geo_railways_2_travelType',
       'offer_geo_railways_3_name', 'offer_geo_railways_3_time',
       'offer_geo_railways_3_travelType', 'offer_geo_railways_4_name',
       'offer_geo_railways_4_time', 'offer_geo_railways_4_travelType',
       'offer_geo_railways_5_name', 'offer_geo_railways_5_time',
       'offer_geo_railways_5_travelType', 'offer_geo_railways_6_name',
       'offer_geo_railways_6_time', 'offer_geo_railways_6_travelType',
       'offer_geo_undergrounds_1_lineColor', 'offer_geo_undergrounds_1_name',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3', 'mp_br', 'mp_cs', 'mp_gs', 'mp_m',
       'mp_sm', 'mp_t', 'mp_k', 'mp_p', 'mp_u', 'mp_h', 'mp_oc', 'mp'],
      dtype='object')

In [113]:
df_train1=df_train.drop(columns=['demandJsonQuery_price_gte','demandJsonQuery_price_lte','offer_bargainTerms_price','offer_geo_railways_1_name','offer_geo_railways_2_name','offer_geo_railways_3_name','offer_geo_railways_4_name','offer_geo_railways_5_name','offer_geo_railways_6_name','offer_geo_undergrounds_1_name','agent_accountType','bti_district_avgHouseAge','bti_district_districtTitle','bti_district_priceSqm','bti_district_priceSqmDiff','bti_district_roomRentPrice','bti_district_roomRentPriceDiff','bti_district_roomSalePrice','bti_district_roomSalePriceDiff','bti_house_entrances','bti_house_flatCount','bti_house_floorMax','bti_house_lifts','bti_house_priceCian','bti_house_priceCianMax','bti_house_priceCianMin','bti_house_priceSqm','bti_house_priceSqmDiff','bti_house_roomRentPrice','bti_house_roomRentPriceDiff','bti_house_yearRelease','offer_building_cargoLiftsCount'])

In [114]:
df_train1.columns

Index(['Unnamed: 0', 'District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_offersCount', 'agent_userTrustLevel',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_houseGasSupplyType',
       'bti_house_houseHeatSupplyType', 'bti_house_houseMaterialType',
       'bti_house_houseOverlapType', 'offer_bargainTerms_mortgageAllowed',
       'offer_building_floorsCount', 'offer_building_totalArea',
       'offer_floorNumber', 'offer_geo_coordinates_lat',
       'offer_geo_coordinates_lng', 'offer_geo_railways_1_time',
       'offer_geo_railways_1_travelType', 'offer_geo_railways_2_time',
       'offer_geo_railways_2_travelType', 'offer_geo_railways_3_time',
       'offer_geo_railways_3_travelType', 'offer_geo_railways_4_time',
       'offer_geo_railways_4_travelType', 'offer_geo_railways_5_time',
       'offer_geo_railways_5_travelType', 'offer_geo_railways_6_time',
       'offer_geo_railways_6_travelType', 'offer_geo_undergrounds_1_lineColor',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3', 'mp_br', 'mp_cs', 'mp_gs', 'mp_m',
       'mp_sm', 'mp_t', 'mp_k', 'mp_p', 'mp_u', 'mp_h', 'mp_oc', 'mp'],
      dtype='object')

In [115]:
df_train2=df_train1.dropna()
df_train2

,Unnamed: 0,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,...,mp_gs,mp_m,mp_sm,mp_t,mp_k,mp_p,mp_u,mp_h,mp_oc,mp
0,0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,...,95.190480,32.695287,86.773529,23.300874,15.872278,18.884448,81.502214,76.074281,78.754718,668.446279
2,2,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,...,161.082642,36.389239,100.283235,73.234226,34.307251,46.562756,200.941529,237.509835,207.544682,1538.713908
5,5,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,...,137.026135,31.092774,82.500511,46.881563,26.002787,43.840758,158.191425,165.285655,153.730691,1162.250554
6,6,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,...,62.016897,33.437010,83.693577,17.871042,17.364766,29.964729,64.073516,63.909290,60.188458,559.238144
7,7,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,...,166.407553,34.325866,87.711940,46.118187,23.727315,37.297572,156.194827,148.258425,143.563226,1111.316426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51584,51584,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,...,65.395246,22.030286,62.494478,21.705996,17.152825,28.909747,76.860989,75.326765,78.195910,596.665606
51585,51585,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,...,148.029413,32.995538,88.570743,30.202956,17.906718,19.946484,105.133421,105.201570,113.208751,872.339851
51586,51586,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,...,90.844283,32.335390,474.698703,27.944573,20.657448,32.844238,99.487188,288.772605,97.468580,1399.602043
51587,51587,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,...,157.870324,31.308698,103.905542,59.665138,25.093171,43.005483,203.336200,207.235407,208.379714,1418.570406
51588,51588,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,...,76.345518,25.028516,73.651870,26.828472,18.565519,34.953011,92.365431,91.822525,91.754793,707.600795

In [122]:
rail_1_byFoot=np.array([])
rail_1_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_1_travelType,df_train4.offer_geo_railways_1_time):
    if i == 'byFoot':
        rail_1_byFoot=np.append(rail_1_byFoot, df_train4.offer_geo_railways_1_time[j])
        rail_1_byCar=np.append(rail_1_byCar, 0)
    elif i == 'byCar':
        rail_1_byCar=np.append(rail_1_byCar, df_train4.offer_geo_railways_1_time[j])
        rail_1_byFoot=np.append(rail_1_byFoot, 0)
byFoot1=list(rail_1_byFoot)
byCar1=list(rail_1_byCar)
df_train4['byFoot1']=byFoot1
df_train4['byCar1']=byCar1
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,mp_sm,mp_t,mp_k,mp_p,mp_u,mp_h,mp_oc,mp,byFoot1,byCar1
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,86.773529,23.300874,15.872278,18.884448,81.502214,76.074281,78.754718,668.446279,34.0,0.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,100.283235,73.234226,34.307251,46.562756,200.941529,237.509835,207.544682,1538.713908,29.0,0.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,82.500511,46.881563,26.002787,43.840758,158.191425,165.285655,153.730691,1162.250554,3.0,0.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,83.693577,17.871042,17.364766,29.964729,64.073516,63.909290,60.188458,559.238144,6.0,0.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,87.711940,46.118187,23.727315,37.297572,156.194827,148.258425,143.563226,1111.316426,0.0,40.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,62.494478,21.705996,17.152825,28.909747,76.860989,75.326765,78.195910,596.665606,23.0,0.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,88.570743,30.202956,17.906718,19.946484,105.133421,105.201570,113.208751,872.339851,30.0,0.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,474.698703,27.944573,20.657448,32.844238,99.487188,288.772605,97.468580,1399.602043,0.0,59.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,103.905542,59.665138,25.093171,43.005483,203.336200,207.235407,208.379714,1418.570406,38.0,0.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,73.651870,26.828472,18.565519,34.953011,92.365431,91.822525,91.754793,707.600795,15.0,0.0

In [123]:
rail_2_byFoot=np.array([])
rail_2_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_2_travelType,df_train4.offer_geo_railways_2_time):
    if i == 'byFoot':
        rail_2_byFoot=np.append(rail_2_byFoot, df_train4.offer_geo_railways_2_time[j])
        rail_2_byCar=np.append(rail_2_byCar, 0)
    elif i == 'byCar':
        rail_2_byCar=np.append(rail_2_byCar, df_train4.offer_geo_railways_2_time[j])
        rail_2_byFoot=np.append(rail_2_byFoot, 0)
byFoot2=list(rail_2_byFoot)
byCar2=list(rail_2_byCar)
df_train4['byFoot2']=byFoot2
df_train4['byCar2']=byCar2
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,mp_k,mp_p,mp_u,mp_h,mp_oc,mp,byFoot1,byCar1,byFoot2,byCar2
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,15.872278,18.884448,81.502214,76.074281,78.754718,668.446279,34.0,0.0,15.0,0.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,34.307251,46.562756,200.941529,237.509835,207.544682,1538.713908,29.0,0.0,0.0,25.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,26.002787,43.840758,158.191425,165.285655,153.730691,1162.250554,3.0,0.0,4.0,0.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,17.364766,29.964729,64.073516,63.909290,60.188458,559.238144,6.0,0.0,0.0,36.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,23.727315,37.297572,156.194827,148.258425,143.563226,1111.316426,0.0,40.0,28.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,17.152825,28.909747,76.860989,75.326765,78.195910,596.665606,23.0,0.0,0.0,36.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,17.906718,19.946484,105.133421,105.201570,113.208751,872.339851,30.0,0.0,108.0,0.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,20.657448,32.844238,99.487188,288.772605,97.468580,1399.602043,0.0,59.0,2.0,0.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,25.093171,43.005483,203.336200,207.235407,208.379714,1418.570406,38.0,0.0,33.0,0.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,18.565519,34.953011,92.365431,91.822525,91.754793,707.600795,15.0,0.0,0.0,36.0

In [124]:
rail_3_byFoot=np.array([])
rail_3_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_3_travelType,df_train4.offer_geo_railways_3_time):
    if i == 'byFoot':
        rail_3_byFoot=np.append(rail_3_byFoot, df_train4.offer_geo_railways_3_time[j])
        rail_3_byCar=np.append(rail_3_byCar, 0)
    elif i == 'byCar':
        rail_3_byCar=np.append(rail_3_byCar, df_train4.offer_geo_railways_3_time[j])
        rail_3_byFoot=np.append(rail_3_byFoot, 0)
byFoot3=list(rail_3_byFoot)
byCar3=list(rail_3_byCar)
df_train4['byFoot3']=byFoot3
df_train4['byCar3']=byCar3
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,mp_u,mp_h,mp_oc,mp,byFoot1,byCar1,byFoot2,byCar2,byFoot3,byCar3
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,81.502214,76.074281,78.754718,668.446279,34.0,0.0,15.0,0.0,63.0,0.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,200.941529,237.509835,207.544682,1538.713908,29.0,0.0,0.0,25.0,23.0,0.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,158.191425,165.285655,153.730691,1162.250554,3.0,0.0,4.0,0.0,0.0,21.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,64.073516,63.909290,60.188458,559.238144,6.0,0.0,0.0,36.0,0.0,54.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,156.194827,148.258425,143.563226,1111.316426,0.0,40.0,28.0,0.0,0.0,54.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,76.860989,75.326765,78.195910,596.665606,23.0,0.0,0.0,36.0,0.0,73.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,105.133421,105.201570,113.208751,872.339851,30.0,0.0,108.0,0.0,49.0,0.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,99.487188,288.772605,97.468580,1399.602043,0.0,59.0,2.0,0.0,8.0,0.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,203.336200,207.235407,208.379714,1418.570406,38.0,0.0,33.0,0.0,0.0,48.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,92.365431,91.822525,91.754793,707.600795,15.0,0.0,0.0,36.0,37.0,0.0

In [126]:
rail_4_byFoot=np.array([])
rail_4_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_4_travelType,df_train4.offer_geo_railways_4_time):
    if i == 'byFoot':
        rail_4_byFoot=np.append(rail_4_byFoot, df_train4.offer_geo_railways_4_time[j])
        rail_4_byCar=np.append(rail_4_byCar, 0)
    elif i == 'byCar':
        rail_4_byCar=np.append(rail_4_byCar, df_train4.offer_geo_railways_4_time[j])
        rail_4_byFoot=np.append(rail_4_byFoot, 0)
byFoot4=list(rail_4_byFoot)
byCar4=list(rail_4_byCar)
df_train4['byFoot4']=byFoot4
df_train4['byCar4']=byCar4
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,mp_oc,mp,byFoot1,byCar1,byFoot2,byCar2,byFoot3,byCar3,byFoot4,byCar4
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,78.754718,668.446279,34.0,0.0,15.0,0.0,63.0,0.0,0.0,44.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,207.544682,1538.713908,29.0,0.0,0.0,25.0,23.0,0.0,37.0,0.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,153.730691,1162.250554,3.0,0.0,4.0,0.0,0.0,21.0,65.0,0.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,60.188458,559.238144,6.0,0.0,0.0,36.0,0.0,54.0,76.0,0.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,143.563226,1111.316426,0.0,40.0,28.0,0.0,0.0,54.0,40.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,78.195910,596.665606,23.0,0.0,0.0,36.0,0.0,73.0,65.0,0.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,113.208751,872.339851,30.0,0.0,108.0,0.0,49.0,0.0,0.0,22.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,97.468580,1399.602043,0.0,59.0,2.0,0.0,8.0,0.0,41.0,0.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,208.379714,1418.570406,38.0,0.0,33.0,0.0,0.0,48.0,19.0,0.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,91.754793,707.600795,15.0,0.0,0.0,36.0,37.0,0.0,39.0,0.0

In [127]:
rail_5_byFoot=np.array([])
rail_5_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_5_travelType,df_train4.offer_geo_railways_5_time):
    if i == 'byFoot':
        rail_5_byFoot=np.append(rail_5_byFoot, df_train4.offer_geo_railways_5_time[j])
        rail_5_byCar=np.append(rail_5_byCar, 0)
    elif i == 'byCar':
        rail_5_byCar=np.append(rail_5_byCar, df_train4.offer_geo_railways_5_time[j])
        rail_5_byFoot=np.append(rail_5_byFoot, 0)
byFoot5=list(rail_5_byFoot)
byCar5=list(rail_5_byCar)
df_train4['byFoot5']=byFoot5
df_train4['byCar5']=byCar5
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,byFoot1,byCar1,byFoot2,byCar2,byFoot3,byCar3,byFoot4,byCar4,byFoot5,byCar5
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,34.0,0.0,15.0,0.0,63.0,0.0,0.0,44.0,0.0,40.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,29.0,0.0,0.0,25.0,23.0,0.0,37.0,0.0,0.0,5.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,3.0,0.0,4.0,0.0,0.0,21.0,65.0,0.0,0.0,7.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,6.0,0.0,0.0,36.0,0.0,54.0,76.0,0.0,0.0,5.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,0.0,40.0,28.0,0.0,0.0,54.0,40.0,0.0,0.0,64.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,23.0,0.0,0.0,36.0,0.0,73.0,65.0,0.0,7.0,0.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,30.0,0.0,108.0,0.0,49.0,0.0,0.0,22.0,0.0,7.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,0.0,59.0,2.0,0.0,8.0,0.0,41.0,0.0,0.0,7.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,38.0,0.0,33.0,0.0,0.0,48.0,19.0,0.0,0.0,5.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,15.0,0.0,0.0,36.0,37.0,0.0,39.0,0.0,0.0,7.0

In [128]:
rail_6_byFoot=np.array([])
rail_6_byCar=np.array([])
for i,j in zip(df_train4.offer_geo_railways_6_travelType,df_train4.offer_geo_railways_6_time):
    if i == 'byFoot':
        rail_6_byFoot=np.append(rail_6_byFoot, df_train4.offer_geo_railways_6_time[j])
        rail_6_byCar=np.append(rail_6_byCar, 0)
    elif i == 'byCar':
        rail_6_byCar=np.append(rail_6_byCar, df_train4.offer_geo_railways_6_time[j])
        rail_6_byFoot=np.append(rail_6_byFoot, 0)
byFoot6=list(rail_6_byFoot)
byCar6=list(rail_6_byCar)
df_train4['byFoot6']=byFoot6
df_train4['byCar6']=byCar6
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,byFoot2,byCar2,byFoot3,byCar3,byFoot4,byCar4,byFoot5,byCar5,byFoot6,byCar6
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,15.0,0.0,63.0,0.0,0.0,44.0,0.0,40.0,0.0,10.0
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,0.0,25.0,23.0,0.0,37.0,0.0,0.0,5.0,0.0,11.0
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,4.0,0.0,0.0,21.0,65.0,0.0,0.0,7.0,0.0,11.0
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,0.0,36.0,0.0,54.0,76.0,0.0,0.0,5.0,8.0,0.0
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,28.0,0.0,0.0,54.0,40.0,0.0,0.0,64.0,22.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,0.0,36.0,0.0,73.0,65.0,0.0,7.0,0.0,0.0,11.0
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,108.0,0.0,49.0,0.0,0.0,22.0,0.0,7.0,0.0,11.0
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,2.0,0.0,8.0,0.0,41.0,0.0,0.0,7.0,0.0,11.0
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,33.0,0.0,0.0,48.0,19.0,0.0,0.0,5.0,0.0,14.0
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,0.0,36.0,37.0,0.0,39.0,0.0,0.0,7.0,0.0,14.0

In [129]:
df_train5=df_train4.drop(columns=['offer_geo_railways_1_travelType','offer_geo_railways_1_time','offer_geo_railways_2_time','offer_geo_railways_2_travelType','offer_geo_railways_3_time','offer_geo_railways_3_travelType','offer_geo_railways_4_time','offer_geo_railways_4_travelType','offer_geo_railways_5_time','offer_geo_railways_5_travelType','offer_geo_railways_6_time','offer_geo_railways_6_travelType'])

In [131]:
df_train5.columns

Index(['District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_offersCount', 'agent_userTrustLevel',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_houseGasSupplyType',
       'bti_house_houseHeatSupplyType', 'bti_house_houseMaterialType',
       'bti_house_houseOverlapType', 'offer_bargainTerms_mortgageAllowed',
       'offer_building_floorsCount', 'offer_building_totalArea',
       'offer_floorNumber', 'offer_geo_coordinates_lat',
       'offer_geo_coordinates_lng', 'offer_geo_undergrounds_1_lineColor',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3', 'mp_br', 'mp_cs', 'mp_gs', 'mp_m',
       'mp_sm', 'mp_t', 'mp_k', 'mp_p', 'mp_u', 'mp_h', 'mp_oc', 'mp',
       'byFoot1', 'byCar1', 'byFoot2', 'byCar2', 'byFoot3', 'byCar3',
       'byFoot4', 'byCar4', 'byFoot5', 'byCar5', 'byFoot6', 'byCar6'],
      dtype='object')

In [116]:
df_train3=df_train2.reset_index()
df_train4=df_train3.drop(columns=['Unnamed: 0','index'])
df_train4

,District1,ad_objectType,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,agent_userTrustLevel,bti_house_demolishedInMoscowProgramm,bti_house_houseGasSupplyType,bti_house_houseHeatSupplyType,...,mp_gs,mp_m,mp_sm,mp_t,mp_k,mp_p,mp_u,mp_h,mp_oc,mp
0,ЮВАО,flat_old,18800000.0,3.0,5364.0,5.0,notInvolved,0.0,without,central,...,95.190480,32.695287,86.773529,23.300874,15.872278,18.884448,81.502214,76.074281,78.754718,668.446279
1,ЦАО,flat_old,55000000.0,0.0,2745.0,31.0,involved,0.0,unknown,none,...,161.082642,36.389239,100.283235,73.234226,34.307251,46.562756,200.941529,237.509835,207.544682,1538.713908
2,ЗАО,flat_old,42000000.0,0.0,2176.0,5.0,notInvolved,0.0,unknown,none,...,137.026135,31.092774,82.500511,46.881563,26.002787,43.840758,158.191425,165.285655,153.730691,1162.250554
3,ЮАО,flat_old,9000000.0,3.0,1102.0,8.0,notInvolved,0.0,central,central,...,62.016897,33.437010,83.693577,17.871042,17.364766,29.964729,64.073516,63.909290,60.188458,559.238144
4,СВАО,flat_old,8399000.0,1.0,6371.0,13.0,involved,0.0,without,central,...,166.407553,34.325866,87.711940,46.118187,23.727315,37.297572,156.194827,148.258425,143.563226,1111.316426
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,ЗАО,flat_old,24900000.0,0.0,2907.0,37.0,involved,0.0,without,central,...,65.395246,22.030286,62.494478,21.705996,17.152825,28.909747,76.860989,75.326765,78.195910,596.665606
37414,ВАО,flat_old,7850000.0,15.0,10527.0,6.0,notInvolved,0.0,central,central,...,148.029413,32.995538,88.570743,30.202956,17.906718,19.946484,105.133421,105.201570,113.208751,872.339851
37415,ЮЗАО,flat_old,32500000.0,0.0,2409.0,19.0,involved,0.0,without,itp,...,90.844283,32.335390,474.698703,27.944573,20.657448,32.844238,99.487188,288.772605,97.468580,1399.602043
37416,САО,flat_old,1275000.0,2.0,3513.0,36.0,involved,0.0,unknown,none,...,157.870324,31.308698,103.905542,59.665138,25.093171,43.005483,203.336200,207.235407,208.379714,1418.570406
37417,СЗАО,flat_old,33500000.0,7.0,1839.0,26.0,involved,0.0,without,central,...,76.345518,25.028516,73.651870,26.828472,18.565519,34.953011,92.365431,91.822525,91.754793,707.600795

In [120]:
df_train4.columns

Index(['District1', 'ad_objectType', 'ad_price', 'ad_stat_daily',
       'ad_stat_total', 'agent_offersCount', 'agent_userTrustLevel',
       'bti_house_demolishedInMoscowProgramm', 'bti_house_houseGasSupplyType',
       'bti_house_houseHeatSupplyType', 'bti_house_houseMaterialType',
       'bti_house_houseOverlapType', 'offer_bargainTerms_mortgageAllowed',
       'offer_building_floorsCount', 'offer_building_totalArea',
       'offer_floorNumber', 'offer_geo_coordinates_lat',
       'offer_geo_coordinates_lng', 'offer_geo_railways_1_time',
       'offer_geo_railways_1_travelType', 'offer_geo_railways_2_time',
       'offer_geo_railways_2_travelType', 'offer_geo_railways_3_time',
       'offer_geo_railways_3_travelType', 'offer_geo_railways_4_time',
       'offer_geo_railways_4_travelType', 'offer_geo_railways_5_time',
       'offer_geo_railways_5_travelType', 'offer_geo_railways_6_time',
       'offer_geo_railways_6_travelType', 'offer_geo_undergrounds_1_lineColor',
       'offer_geo_undergrounds_1_travelTime',
       'offer_geo_undergrounds_1_travelType',
       'offer_geo_undergrounds_1_underConstruction', 'offer_roomsCount',
       'offer_similarOffersCount', 'offer_totalArea',
       'offer_valueAddedServices_isTop3', 'mp_br', 'mp_cs', 'mp_gs', 'mp_m',
       'mp_sm', 'mp_t', 'mp_k', 'mp_p', 'mp_u', 'mp_h', 'mp_oc', 'mp'],
      dtype='object')

In [132]:
df_train6=pd.get_dummies(df_train5, columns=['offer_geo_undergrounds_1_lineColor','offer_geo_undergrounds_1_travelType','District1','ad_objectType','agent_userTrustLevel','bti_house_houseGasSupplyType','bti_house_houseHeatSupplyType','bti_house_houseMaterialType','bti_house_houseOverlapType','offer_valueAddedServices_isTop3'])

In [133]:
df_train6

,ad_price,ad_stat_daily,ad_stat_total,agent_offersCount,bti_house_demolishedInMoscowProgramm,offer_bargainTerms_mortgageAllowed,offer_building_floorsCount,offer_building_totalArea,offer_floorNumber,offer_geo_coordinates_lat,...,bti_house_houseMaterialType_none,bti_house_houseMaterialType_panel,bti_house_houseMaterialType_wood,bti_house_houseOverlapType_concrete,bti_house_houseOverlapType_mixed,bti_house_houseOverlapType_other,bti_house_houseOverlapType_unknown,bti_house_houseOverlapType_wood,offer_valueAddedServices_isTop3_False,offer_valueAddedServices_isTop3_True
0,18800000.0,3.0,5364.0,5.0,0.0,1.0,14,106.0,13,55.668198,...,0,1,0,1,0,0,0,0,1,0
1,55000000.0,0.0,2745.0,31.0,0.0,1.0,73,108.5,34,55.747115,...,1,0,0,0,0,0,1,0,1,0
2,42000000.0,0.0,2176.0,5.0,0.0,0.0,17,86.0,2,55.726918,...,1,0,0,0,0,0,1,0,1,0
3,9000000.0,3.0,1102.0,8.0,0.0,1.0,12,48.0,5,55.607667,...,1,0,0,1,0,0,0,0,1,0
4,8399000.0,1.0,6371.0,13.0,0.0,0.0,22,37.7,1,55.822544,...,0,1,0,1,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37413,24900000.0,0.0,2907.0,37.0,0.0,0.0,18,76.2,4,55.747323,...,0,0,0,1,0,0,0,0,1,0
37414,7850000.0,15.0,10527.0,6.0,0.0,1.0,9,45.0,9,55.760226,...,0,0,0,1,0,0,0,0,1,0
37415,32500000.0,0.0,2409.0,19.0,0.0,1.0,40,80.0,31,55.665639,...,0,0,0,1,0,0,0,0,1,0
37416,1275000.0,2.0,3513.0,36.0,0.0,1.0,12,128.0,4,55.793272,...,0,0,0,1,0,0,0,0,1,0
37417,33500000.0,7.0,1839.0,26.0,0.0,1.0,35,113.0,22,55.807461,...,0,0,0,1,0,0,0,0,1,0

In [6]:
df=df_train6.copy()

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37418 entries, 0 to 37417
Columns: 104 entries, Unnamed: 0 to offer_valueAddedServices_isTop3_True
dtypes: float64(16), int64(88)
memory usage: 29.7 MB

In [8]:
# обязательный код
X=df.drop(columns=['ad_price','offer_building_totalArea','mp_br','mp_cs','mp_gs','mp_m','mp_sm','mp_t','mp_k','mp_p','mp_u','mp_h','mp_oc']).values
y=df.ad_price.values
# сплитуйте X и y как хотите
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, 
                                                    shuffle=True)

In [8]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import confusion_matrix, classification_report, f1_score

pipe = Pipeline([('preprocessing', MinMaxScaler()),   
                 ('classifier', RandomForestClassifier(n_estimators=100, max_features = 7, 
                                                           max_depth=10, random_state=0))])

model = pipe
model.fit(X_train, y_train) 
y_pred=model.predict(X_test)
print('Правильность на обучающем наборе: {:.5f}'.format(model.score(X_train, y_train)))
print('Правильность на тестовом наборе: {:.5f}'.format(model.score(X_test, y_test)))
print("Precision Score : ",precision_score(y_test, y_pred, 
                                           pos_label='positive',
                                           average='micro'))
print("Recall Score : ",recall_score(y_test, y_pred, 
                                           pos_label='positive',
                                           average='micro'))

Правильность на обучающем наборе: 0.44128
Правильность на тестовом наборе: 0.04478
Precision Score :  0.04478458049886622
Recall Score :  0.04478458049886622

C:\Users\ianaf\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1321: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)

In [9]:
from sklearn.metrics import confusion_matrix, classification_report, f1_score

pipe = Pipeline([('preprocessing', MinMaxScaler()),   
                 ('classifier', RandomForestClassifier(n_estimators=100, max_features = 6, 
                                                           max_depth=10, random_state=0, criterion='entropy', min_samples_split=5))])

model = pipe
model.fit(X_train, y_train) 
y_pred=model.predict(X_test)
print('Правильность на обучающем наборе: {:.5f}'.format(model.score(X_train, y_train)))
print('Правильность на тестовом наборе: {:.5f}'.format(model.score(X_test, y_test)))
print("Precision Score : ",precision_score(y_test, y_pred, 
                                           average='micro'))
print("Recall Score : ",recall_score(y_test, y_pred, 
                                           average='micro'))

Правильность на обучающем наборе: 0.81193
Правильность на тестовом наборе: 0.05645
Precision Score :  0.05644638807904114
Recall Score :  0.05644638807904114

In [9]:
rf = RandomForestRegressor(random_state = 42)
from pprint import pprint
# Look at parameters used by our current forest
print('Parameters currently in use:\n')
pprint(rf.get_params())

Parameters currently in use:

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'criterion': 'mse',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': 42,
 'verbose': 0,
 'warm_start': False}

In [10]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1600, num = 9)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 90, num = 9)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
pprint(random_grid)

{'bootstrap': [True, False],
 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, None],
 'max_features': ['auto', 'sqrt'],
 'min_samples_leaf': [1, 2, 4],
 'min_samples_split': [2, 5, 10],
 'n_estimators': [100, 287, 475, 662, 850, 1037, 1225, 1412, 1600]}

In [11]:
# Use the random grid to search for best hyperparameters
# First create the base model to tune
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 100, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train, y_train)

Fitting 3 folds for each of 100 candidates, totalling 300 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:  9.5min
[Parallel(n_jobs=-1)]: Done 138 tasks      | elapsed: 45.6min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed: 104.8min finished

RandomizedSearchCV(cv=3, error_score=nan,
                   estimator=RandomForestRegressor(bootstrap=True,
                                                   ccp_alpha=0.0,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features='auto',
                                                   max_leaf_nodes=None,
                                                   max_samples=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   n_estimators=100,
                                                   n_jobs=None, oob_score=Fals...
                   iid='deprecated', n_iter=100, n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [10, 20, 30, 40, 50, 60,
                                                      70, 80, 90, None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4],
                                        'min_samples_split': [2, 5, 10],
                                        'n_estimators': [100, 287, 475, 662,
                                                         850, 1037, 1225, 1412,
                                                         1600]},
                   pre_dispatch='2*n_jobs', random_state=42, refit=True,
                   return_train_score=False, scoring=None, verbose=2)

In [12]:
rf_random.best_params_

{'n_estimators': 662,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'max_features': 'sqrt',
 'max_depth': 90,
 'bootstrap': False}

In [13]:
def evaluate(model, X_test, y_test):
    predictions = model.predict(X_test)
    errors = abs(predictions - y_test)
    mape = 100 * np.mean(errors / y_test)
    accuracy = 100 - mape
    print('Model Performance')
    print('Average Error: {:0.4f} degrees.'.format(np.mean(errors)))
    print('Accuracy = {:0.2f}%.'.format(accuracy))
    
    return accuracy

In [14]:
base_model = RandomForestRegressor(n_estimators = 10, random_state = 42)
base_model.fit(X_train, y_train)
base_accuracy = evaluate(base_model, X_test, y_test)

Model Performance
Average Error: 3367060.4130 degrees.
Accuracy = 41.53%.

In [15]:
best_random = rf_random.best_estimator_
random_accuracy = evaluate(best_random, X_test, y_test)

Model Performance
Average Error: 3156069.4777 degrees.
Accuracy = 44.60%.

In [16]:
print('Improvement of {:0.2f}%.'.format( 100 * (random_accuracy - base_accuracy) / base_accuracy))

Improvement of 7.39%.

In [ ]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [157]:
df_train6.to_excel('df_train6.xlsx')

In [158]:
#{'n_estimators': 1000,
 #'min_samples_split': 5,
 #'min_samples_leaf': 1,
 #'max_features': 'sqrt',
 #'max_depth': 60,
 #'bootstrap': False}

In [ ]:
#Model Performance
#Average Error: 2864549.2767 degrees
#Accuracy = 46.43%.

In [ ]:
#{'n_estimators': 1600,
 #'min_samples_split': 2,
 #'min_samples_leaf': 1,
 #'max_features': 'sqrt',
 #'max_depth': 60,
 #'bootstrap': False}

In [ ]:
#{'n_estimators': 1600,
 #'min_samples_split': 5,
 #'min_samples_leaf': 1,
 #'max_features': 'sqrt',
 #'max_depth': 70,
 #'bootstrap': False}

In [ ]:
#Model Performance
#Average Error: 2852580.2266 degrees.
#Accuracy = 47.21%.

In [4]:
df_train6 = pd.read_excel('df_train6.xlsx')
print(df_train6)

       Unnamed: 0  ad_price  ad_stat_daily  ad_stat_total  agent_offersCount  \
0               0  18800000              3           5364                  5
1               1  55000000              0           2745                 31
2               2  42000000              0           2176                  5
3               3   9000000              3           1102                  8
4               4   8399000              1           6371                 13
...           ...       ...            ...            ...                ...
37413       37413  24900000              0           2907                 37
37414       37414   7850000             15          10527                  6
37415       37415  32500000              0           2409                 19
37416       37416   1275000              2           3513                 36
37417       37417  33500000              7           1839                 26

       bti_house_demolishedInMoscowProgramm  \
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
...                                     ...
37413                                     0
37414                                     0
37415                                     0
37416                                     0
37417                                     0

       offer_bargainTerms_mortgageAllowed  offer_building_floorsCount  \
0                                       1                          14
1                                       1                          73
2                                       0                          17
3                                       1                          12
4                                       0                          22
...                                   ...                         ...
37413                                   0                          18
37414                                   1                           9
37415                                   1                          40
37416                                   1                          12
37417                                   1                          35

       offer_building_totalArea  offer_floorNumber  ...  \
0                         106.0                 13  ...
1                         108.5                 34  ...
2                          86.0                  2  ...
3                          48.0                  5  ...
4                          37.7                  1  ...
...                         ...                ...  ...
37413                      76.2                  4  ...
37414                      45.0                  9  ...
37415                      80.0                 31  ...
37416                     128.0                  4  ...
37417                     113.0                 22  ...

       bti_house_houseMaterialType_none  bti_house_houseMaterialType_panel  \
0                                     0                                  1
1                                     1                                  0
2                                     1                                  0
3                                     1                                  0
4                                     0                                  1
...                                 ...                                ...
37413                                 0                                  0
37414                                 0                                  0
37415                                 0                                  0
37416                                 0                                  0
37417                                 0                                  0

       bti_house_houseMaterialType_wood  bti_house_houseOverlapType_concrete  \
0                                     0                                    1
1                                     0                                    0
2                                     0                                    0
3                                     0                                    1
4                                     0                                    1
...                                 ...                                  ...
37413                                 0                                    1
37414                                 0                                    1
37415                                 0                                    1
37416                                 0                                    1
37417                                 0                                    1

       bti_house_houseOverlapType_mixed  bti_house_houseOverlapType_other  \
0                                     0                                 0
1                                     0                                 0
2                                     0                                 0
3                                     0                                 0
4                                     0                                 0
...                                 ...                               ...
37413                                 0                                 0
37414                                 0                                 0
37415                                 0                                 0
37416                                 0                                 0
37417                                 0                                 0

       bti_house_houseOverlapType_unknown  bti_house_houseOverlapType_wood  \
0                                       0                                0
1                                       1                                0
2                                       1                                0
3                                       0                                0
4                                       0                                0
...                                   ...                              ...
37413                                   0                                0
37414                                   0                                0
37415                                   0                                0
37416                                   0                                0
37417                                   0                                0

       offer_valueAddedServices_isTop3_False  \
0                                          1
1                                          1
2                                          1
3                                          1
4                                          1
...                                      ...
37413                                      1
37414                                      1
37415                                      1
37416                                      1
37417                                      1

       offer_valueAddedServices_isTop3_True
0                                         0
1                                         0
2                                         0
3                                         0
4                                         0
...                                     ...
37413                                     0
37414                                     0
37415                                     0
37416                                     0
37417                                     0

[37418 rows x 104 columns]

In [5]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [False, True],
    'max_depth': [50, 60, 70, 80, None],
    'max_features': ['sqrt'],
    'min_samples_leaf': [1, 2],
    'min_samples_split': [2, 5],
    'n_estimators': [1200, 1400]
}
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)

In [ ]:
# Fit the grid search to the data
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 80 candidates, totalling 240 fits

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 12 concurrent workers.

In [10]:
grid_search.best_params_

{'bootstrap': False,
 'max_depth': None,
 'max_features': 'sqrt',
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'n_estimators': 1400}

In [13]:
best_grid = grid_search.best_estimator_
grid_accuracy = evaluate(best_grid, X_test, y_test)

Model Performance
Average Error: 3039682.8798 degrees.
Accuracy = 46.42%.

In [16]:
print('Improvement of {:0.2f}%.'.format( 100 * (grid_accuracy - base_accuracy) / base_accuracy))

Improvement of 6.86%.

In [ ]:
#{'bootstrap': False,
# 'max_depth': None,
# 'max_features': 'sqrt',
# 'min_samples_leaf': 1,
# 'min_samples_split': 2,
# 'n_estimators': 1400}